<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.NpzxPRw.Domain\Entity\House' shared service.

include_once \dirname(__DIR__, 4).'/src/Domain/Entity/House.php';

return $this->privates['.errored..service_locator.NpzxPRw.Domain\\Entity\\House'] = new \Domain\Entity\House();
