<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'UI\Controller\UserController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/HandleTrait.php';
include_once \dirname(__DIR__, 4).'/src/UI/Controller/UserController.php';

$this->services['UI\\Controller\\UserController'] = $instance = new \UI\Controller\UserController(($this->services['messenger.default_bus'] ?? $this->load('getMessenger_DefaultBusService.php')), ($this->services['jms_serializer'] ?? $this->load('getJmsSerializerService.php')));

$instance->setContainer(($this->privates['.service_locator.pNNo5z3'] ?? $this->load('get_ServiceLocator_PNNo5z3Service.php'))->withContext('UI\\Controller\\UserController', $this));

return $instance;
