services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # COMMAND HANDLERS
  Application\Command\User\CreateUserCommandHandler:
    tags:
      - { name: command_handler, handles: Application\Command\User\CreateUserCommand }