services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  user_repository:
    class: Infrastructure\Repository\UserRepository
    arguments: ['@doctrine', '@logger']

  Application\Repository\UserRepositoryInterface: '@user_repository'