<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7Jd6Z2T' shared service.

return $this->privates['.service_locator.7Jd6Z2T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'house' => ['privates', '.errored..service_locator.7Jd6Z2T.Domain\\Entity\\House', NULL, 'Cannot autowire service ".service_locator.7Jd6Z2T": it references class "Domain\\Entity\\House" but no such service exists.'],
], [
    'house' => 'Domain\\Entity\\House',
]);
