<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BBQXAUI' shared service.

return $this->privates['.service_locator.BBQXAUI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'UI\\Controller\\DeviceController::attach' => ['privates', '.service_locator.7Jd6Z2T', 'get_ServiceLocator_7Jd6Z2TService.php', true],
    'UI\\Controller\\DeviceController:attach' => ['privates', '.service_locator.7Jd6Z2T', 'get_ServiceLocator_7Jd6Z2TService.php', true],
], [
    'UI\\Controller\\DeviceController::attach' => '?',
    'UI\\Controller\\DeviceController:attach' => '?',
]);
