<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Application\Command\User\CreateUserCommandHandler' shared autowired service.

return $this->services['Application\\Command\\User\\CreateUserCommandHandler'] = new \Application\Command\User\CreateUserCommandHandler(($this->services['Domain\\Service\\User\\UserServiceInterface'] ?? $this->load('getUserServiceInterfaceService.php')), new \Infrastructure\Validator\DataValidator(($this->services['validator'] ?? $this->load('getValidatorService.php'))), ($this->privates['user_repository'] ?? $this->load('getUserRepositoryService.php')));
