<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb' shared service.

return $this->services['doctrine_mongodb'] = new \Doctrine\Bundle\MongoDBBundle\ManagerRegistry('MongoDB', $this->parameters['doctrine_mongodb.odm.connections'], $this->parameters['doctrine_mongodb.odm.document_managers'], 'default', 'default', 'ProxyManager\\Proxy\\GhostObjectInterface', $this);
