<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb.odm.command_logger_registry' shared service.

return $this->services['doctrine_mongodb.odm.command_logger_registry'] = new \Doctrine\Bundle\MongoDBBundle\APM\CommandLoggerRegistry(new RewindableGenerator(function () {
    yield 0 => ($this->privates['doctrine_mongodb.odm.command_logger'] ?? $this->load('getDoctrineMongodb_Odm_CommandLoggerService.php'));
    yield 1 => ($this->privates['doctrine_mongodb.odm.data_collector.command_logger'] ?? ($this->privates['doctrine_mongodb.odm.data_collector.command_logger'] = new \Doctrine\ODM\MongoDB\APM\CommandLogger()));
}, 2));
