<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb.odm.default_document_manager' shared service.

$a = new \Doctrine\ODM\MongoDB\Configuration();

$b = new \Doctrine\Common\Cache\ArrayCache();
$b->setNamespace('sf_mongodb_default_eaaQP_t');
$c = new \Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain();
$c->addDriver(new \Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver(($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()), [0 => '/app/src/Domain/Document']), 'App\\Domain\\Document');

$a->setDocumentNamespaces(['App' => 'App\\Domain\\Document']);
$a->setMetadataCacheImpl($b);
$a->setMetadataDriverImpl($c);
$a->setProxyDir(($this->targetDirs[0].'/doctrine/odm/mongodb/Proxies'));
$a->setProxyNamespace('MongoDBODMProxies');
$a->setAutoGenerateProxyClasses(2);
$a->setHydratorDir(($this->targetDirs[0].'/doctrine/odm/mongodb/Hydrators'));
$a->setHydratorNamespace('Hydrators');
$a->setAutoGenerateHydratorClasses(1);
$a->setDefaultDB($this->getEnv('resolve:MONGODB_DB'));
$a->setDefaultCommitOptions([]);
$a->setDefaultDocumentRepositoryClassName('Doctrine\\ODM\\MongoDB\\Repository\\DocumentRepository');
$a->setDefaultGridFSRepositoryClassName('Doctrine\\ODM\\MongoDB\\Repository\\DefaultGridFSRepository');
$a->setPersistentCollectionDir(($this->targetDirs[0].'/doctrine/odm/mongodb/PersistentCollections'));
$a->setPersistentCollectionNamespace('PersistentCollections');
$a->setAutoGeneratePersistentCollectionClasses(0);
$a->setRepositoryFactory(new \Doctrine\Bundle\MongoDBBundle\Repository\ContainerRepositoryFactory(($this->privates['.service_locator.9_yeNH1'] ?? ($this->privates['.service_locator.9_yeNH1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [], [])))));

$this->services['doctrine_mongodb.odm.default_document_manager'] = $instance = \Doctrine\ODM\MongoDB\DocumentManager::create(($this->services['doctrine_mongodb.odm.default_connection'] ?? $this->load('getDoctrineMongodb_Odm_DefaultConnectionService.php')), $a, new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this));

(new \Doctrine\Bundle\MongoDBBundle\ManagerConfigurator([]))->configure($instance);

return $instance;
