<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.Doctrine\Bundle\MongoDBBundle\Command\LoadDataFixturesDoctrineODMCommand' shared service.

$a = new \Doctrine\Bundle\MongoDBBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures([]);

return $this->services['console.command.public_alias.Doctrine\\Bundle\\MongoDBBundle\\Command\\LoadDataFixturesDoctrineODMCommand'] = new \Doctrine\Bundle\MongoDBBundle\Command\LoadDataFixturesDoctrineODMCommand(($this->services['doctrine_mongodb'] ?? $this->load('getDoctrineMongodbService.php')), ($this->services['kernel'] ?? $this->get('kernel', 2)), $a);
