<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.bus.default.middleware.handle_message' shared service.

$this->privates['messenger.bus.default.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Application\\Command\\User\\CreateUserCommand' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['.messenger.handler_descriptor.kwHg_Mc'] ?? $this->load('get_Messenger_HandlerDescriptor_KwHgMcService.php'));
}, 1)]));

$instance->setLogger(($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));

return $instance;
