<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Domain\Service\User\UserServiceInterface' shared autowired service.

return $this->services['Domain\\Service\\User\\UserServiceInterface'] = new \Application\Service\User\UserService(($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')));
