services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # COMMAND HANDLERS
  Application\Command\User\CreateUserCommandHandler:
    tags:
      - { name: command_handler, handles: Application\Command\User\CreateUserCommand }

  # QUERY HANDLERS
  Application\Query\Device\ListDeviceQueryHandle:
    tags:
      - { name: command_handler, handles: Application\Command\Query\Device\ListDeviceQuery }