services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

#  Application\Service\User\UserService: ~
#
#  Domain\Service\User\UserServiceInterface: '@Application\Service\User\UserService'