version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./:/app
      - ./vendor:/app/vendor
      - ./var/container/log:/var/log/nginx
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - php
      - mongodb
      - postgres
  php:
    container_name: app-php
    build: docker/php
    volumes:
      - ./:/app
      - ./var/container/log:/tmp/xdebug.log
  postgres:
    image: postgres
    container_name: app-postgres
    environment:
      - POSTGRES_USER=${DB_ROOT_USER}
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    restart: "no"
    environment:
      - MONGO_DATA_DIR=/var/mongodb
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=${MONGO_USER}
      - MONGODB_PASS=${MONGO_PASSWORD}
    volumes:
      - ./data/db:/data/mongo
    ports:
      - 27017:27017
#  mysql:
#    image: mysql:5.7
#    restart: "no"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_USER: ${MYSQL_ROOT_USER}
#      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#    ports:
#      - 3309:${MYSQL_PORT}