version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./:/app
      - ./vendor:/app/vendor
      - ./var/container/log:/var/log/nginx
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - php
      - mongodb
      - mysql
  php:
    container_name: app-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/app
      - ./var/container/log:/tmp/xdebug.log
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: "no"
    links:
      - ${MYSQL_HOST}:db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - 8084:80
  mysql:
    image: mysql:5.7
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_ROOT_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3309:${MYSQL_PORT}
  mongodb:
    image: mongo:latest
    restart: "no"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=${MONGO_USER}
      - MONGODB_PASS=${MONGO_PASSWORD}
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017