version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8083:80
    volumes:
      - ./api:/app
      - ./api/vendor:/app/vendor
      - ./var/container/log:/var/log/nginx
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - php
    depends_on:
      - postgres
    tty: true
    networks:
      - default
    env_file:
      - .env
  php:
    container_name: app-php
    build: docker/php
    volumes:
      - ./api:/app
      - ./.env:/app/.env
      - ./var/container/log:/tmp/xdebug.log
    tty: true
    networks:
      - default
  postgres:
    image: postgres
    container_name: app-postgres
    environment:
      - POSTGRES_USER=${DB_ROOT_USER}
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./var/data/postgres:/var/lib/postgresql/data
#  mongodb:
#    image: mongo:latest
#    restart: "no"
#    environment:
#      - MONGO_DATA_DIR=/var/mongodb
#      - MONGO_LOG_DIR=/dev/null
#      - MONGODB_USER=${MONGO_USER}
#      - MONGODB_PASS=${MONGO_PASSWORD}
#    volumes:
#      - ./data/db:/data/mongo
#    ports:
#      - 27017:27017
