security:
    providers:
        user_provider:
            entity:
                class: Domain\Entity\User
    encoders:
        Domain\Entity\User:
            algorithm: auto
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: login
            anonymous: ~
            stateless: true
            json_login:
                check_path:               /login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            provider: user_provider
#            user_checker: App\Security\UserSecurityChecker
            logout:
                path: /logout
                invalidate_session: true
        application:
            pattern:   ^/
            stateless: true
            anonymous: true
            provider: user_provider
#            user_checker: App\Security\UserSecurityChecker
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            logout:
                path: /logout
                invalidate_session: true
        refresh:
            pattern:  ^/token/refresh
            stateless: true
            anonymous: true
        documentation:
            pattern:   ^/docs
            stateless: true
            provider: user_provider
            http_basic: ~
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control: