<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YX5InUt' shared service.

return $this->privates['.service_locator.YX5InUt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'UI\\Controller\\DeviceController::attach' => ['privates', '.service_locator.NpzxPRw', 'get_ServiceLocator_NpzxPRwService.php', true],
    'UI\\Controller\\UserController::getOne' => ['privates', '.service_locator.OKbt_kT', 'get_ServiceLocator_OKbtKTService.php', true],
    'UI\\Controller\\DeviceController:attach' => ['privates', '.service_locator.NpzxPRw', 'get_ServiceLocator_NpzxPRwService.php', true],
    'UI\\Controller\\UserController:getOne' => ['privates', '.service_locator.OKbt_kT', 'get_ServiceLocator_OKbtKTService.php', true],
], [
    'UI\\Controller\\DeviceController::attach' => '?',
    'UI\\Controller\\UserController::getOne' => '?',
    'UI\\Controller\\DeviceController:attach' => '?',
    'UI\\Controller\\UserController:getOne' => '?',
]);
