<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OKbt_kT' shared service.

return $this->privates['.service_locator.OKbt_kT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'user' => ['privates', '.errored..service_locator.OKbt_kT.Domain\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.OKbt_kT": it references class "Domain\\Entity\\User" but no such service exists.'],
], [
    'user' => 'Domain\\Entity\\User',
]);
