<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Application\Command\User\CreateUserCommandHandler' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Application/Command/CommandHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/src/Application/Command/User/CreateUserCommandHandler.php';
include_once \dirname(__DIR__, 4).'/src/Infrastructure/Validator/ValidatorInterface.php';
include_once \dirname(__DIR__, 4).'/src/Infrastructure/Validator/DataValidator.php';

return $this->services['Application\\Command\\User\\CreateUserCommandHandler'] = new \Application\Command\User\CreateUserCommandHandler(($this->services['Domain\\Service\\User\\UserServiceInterface'] ?? $this->load('getUserServiceInterfaceService.php')), new \Infrastructure\Validator\DataValidator(($this->services['validator'] ?? $this->load('getValidatorService.php'))), ($this->privates['user_repository'] ?? $this->load('getUserRepositoryService.php')));
