<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Application\Query\Device\ListDeviceQueryHandle' shared autowired service.

return $this->services['Application\\Query\\Device\\ListDeviceQueryHandle'] = new \Application\Query\Device\ListDeviceQueryHandle();
