<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Domain\Service\User\UserServiceInterface' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Domain/Service/User/UserServiceInterface.php';
include_once \dirname(__DIR__, 4).'/src/Application/Service/User/UserService.php';

return $this->services['Domain\\Service\\User\\UserServiceInterface'] = new \Application\Service\User\UserService(($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')));
