imports:
    - { resource: services/command_handlers.yaml }

parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    UI\Controller\:
        resource: '../src/UI/Controller/*'
        tags: ['controller.service_arguments']

    Application\Service\:
        resource: '../src/Application/Service'