<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMhwy9kI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMhwy9kI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMhwy9kI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMhwy9kI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMhwy9kI\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mhwy9kI',
    'container.build_id' => '4f29639d',
    'container.build_time' => 1580342757,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMhwy9kI');
