<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container158NpuQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container158NpuQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container158NpuQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container158NpuQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container158NpuQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '158NpuQ',
    'container.build_id' => '6dcaa998',
    'container.build_time' => 1573686631,
], __DIR__.\DIRECTORY_SEPARATOR.'Container158NpuQ');
